//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nezam.Modular.ESS.Secretariat.Application.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DocumentTranslates_fa {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DocumentTranslates_fa() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Nezam.Modular.ESS.Secretariat.Application.Resources.DocumentTranslates.fa", typeof(DocumentTranslates_fa).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پیوست اضافه شد..
        /// </summary>
        internal static string AttachmentAdded {
            get {
                return ResourceManager.GetString("AttachmentAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پیوست حذف شد..
        /// </summary>
        internal static string AttachmentRemoved {
            get {
                return ResourceManager.GetString("AttachmentRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پیوست به‌روزرسانی شد..
        /// </summary>
        internal static string AttachmentUpdated {
            get {
                return ResourceManager.GetString("AttachmentUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محتوا به‌روزرسانی شد..
        /// </summary>
        internal static string ContentUpdated {
            get {
                return ResourceManager.GetString("ContentUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سند بایگانی شد..
        /// </summary>
        internal static string DocumentArchived {
            get {
                return ResourceManager.GetString("DocumentArchived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سند با موفقیت ایجاد شد..
        /// </summary>
        internal static string DocumentCreated {
            get {
                return ResourceManager.GetString("DocumentCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سند منتشر شد..
        /// </summary>
        internal static string DocumentPublished {
            get {
                return ResourceManager.GetString("DocumentPublished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سند به پیش‌نویس بازگشت..
        /// </summary>
        internal static string DocumentRevertedToDraft {
            get {
                return ResourceManager.GetString("DocumentRevertedToDraft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارجاع اولیه اضافه شد..
        /// </summary>
        internal static string InitialReferralAdded {
            get {
                return ResourceManager.GetString("InitialReferralAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارجاع اضافه شد..
        /// </summary>
        internal static string ReferralAdded {
            get {
                return ResourceManager.GetString("ReferralAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to به ارجاع پاسخ داده شد..
        /// </summary>
        internal static string ReferralResponded {
            get {
                return ResourceManager.GetString("ReferralResponded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان به‌روزرسانی شد..
        /// </summary>
        internal static string TitleUpdated {
            get {
                return ResourceManager.GetString("TitleUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع سند تغییر کرد..
        /// </summary>
        internal static string TypeChanged {
            get {
                return ResourceManager.GetString("TypeChanged", resourceCulture);
            }
        }
    }
}
